version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile : Dockerfile
    platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - mysql-server
      - redis
    
    command: pm2 start app.js
<<<<<<< HEAD

=======
    
>>>>>>> 283781b (fix: compose 파일에 pm2 start 추가)
  mysql-server:
    image: mysql:8.0

    restart : always

    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name : redis
    ports:
      - "6379:6379"
    restart : always
    
volumes:
  mysql-data:
