name: Deploy to Amazon ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setting .env
        run: |
          pwd
          touch .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "SERVER_HOST=${{ secrets.DB_USER }}" >> .env
          echo "DB_USER=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}">> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "GPT_KEY=${{ secrets.GPT_KEY }}" >> .env
          echo "SENS_SERVICE_ID=${{ secrets.SENS_SERVICE_ID }}" >> .env
          echo "SENS_SESENS_ACCESS_KEYCRET_KEY=${{ secrets.SENS_ACCESS_KEY }}" >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          npm
          npm run build
